### ISSUE TITLE
Document how to install/configure RabbitMQ on Ubuntu/Deb

### ISSUE THREAD

**Issue by JordanP** [sieben/chat_demo#3]
Hi,
So RabbitMQ is nice and all but it's a bit of a beast. After the typical 'apt-get ...' what should I do to rabbitmq config ? How can I create a user ? What's an 'exchange' ? Is 'chat_demo' going to create that exchange at first start ? Or should I create it before hand, and if so how ?

Thanks !

**Comment by sieben** [comment]
RabbitMQ is in the right state for this demo right out of the box.
You can create a specific user using rabbitmqctl add_user foo bar but this not required because every RabbitMQ server comes by default with "guest" user. This account can only connect on localhost. 

For the exchange, there is one created by default as well I'm using an exchange called amq.topic which is created on each virtual host.

**Comment by JordanP** [comment]
ACK, thanks
